package javax.microedition.khronos.egl;

public interface EGL10 extends EGL {
    int EGL_SUCCESS = 12288;
    int EGL_NOT_INITIALIZED = 12289;
    int EGL_BAD_ACCESS = 12290;
    int EGL_BAD_ALLOC = 12291;
    int EGL_BAD_ATTRIBUTE = 12292;
    int EGL_BAD_CONFIG = 12293;
    int EGL_BAD_CONTEXT = 12294;
    int EGL_BAD_CURRENT_SURFACE = 12295;
    int EGL_BAD_DISPLAY = 12296;
    int EGL_BAD_MATCH = 12297;
    int EGL_BAD_NATIVE_PIXMAP = 12298;
    int EGL_BAD_NATIVE_WINDOW = 12299;
    int EGL_BAD_PARAMETER = 12300;
    int EGL_BAD_SURFACE = 12301;
    int EGL_CONTEXT_LOST = 12302;
    int EGL_BUFFER_SIZE = 12320;
    int EGL_ALPHA_SIZE = 12321;
    int EGL_BLUE_SIZE = 12322;
    int EGL_GREEN_SIZE = 12323;
    int EGL_RED_SIZE = 12324;
    int EGL_DEPTH_SIZE = 12325;
    int EGL_STENCIL_SIZE = 12326;
    int EGL_CONFIG_CAVEAT = 12327;
    int EGL_CONFIG_ID = 12328;
    int EGL_LEVEL = 12329;
    int EGL_MAX_PBUFFER_HEIGHT = 12330;
    int EGL_MAX_PBUFFER_PIXELS = 12331;
    int EGL_MAX_PBUFFER_WIDTH = 12332;
    int EGL_NATIVE_RENDERABLE = 12333;
    int EGL_NATIVE_VISUAL_ID = 12334;
    int EGL_NATIVE_VISUAL_TYPE = 12335;
    int EGL_SAMPLES = 12337;
    int EGL_SAMPLE_BUFFERS = 12338;
    int EGL_SURFACE_TYPE = 12339;
    int EGL_TRANSPARENT_TYPE = 12340;
    int EGL_TRANSPARENT_BLUE_VALUE = 12341;
    int EGL_TRANSPARENT_GREEN_VALUE = 12342;
    int EGL_TRANSPARENT_RED_VALUE = 12343;
    int EGL_NONE = 12344;
    int EGL_BIND_TO_TEXTURE_RGB = 12345;
    int EGL_BIND_TO_TEXTURE_RGBA = 12346;
    int EGL_MIN_SWAP_INTERVAL = 12347;
    int EGL_MAX_SWAP_INTERVAL = 12348;
    int EGL_LUMINANCE_SIZE = 12349;
    int EGL_ALPHA_MASK_SIZE = 12350;
    int EGL_COLOR_BUFFER_TYPE = 12351;
    int EGL_RENDERABLE_TYPE = 12352;
    int EGL_WINDOW_BIT = 4;
    int EGL_OPENGL_ES2_BIT = 4;
    int EGL_CONTEXT_CLIENT_VERSION = 12440;
    Object EGL_DEFAULT_DISPLAY = EglObjs.DEFAULT_DISPLAY;
    EGLDisplay EGL_NO_DISPLAY = EglObjs.NO_DISPLAY;
    EGLContext EGL_NO_CONTEXT = EglObjs.NO_CONTEXT;
    EGLSurface EGL_NO_SURFACE = EglObjs.NO_SURFACE;

    boolean eglChooseConfig(EGLDisplay display, int[] attrib, EGLConfig[] configs, int configSize, int[] numConfig);
    EGLContext eglCreateContext(EGLDisplay display, EGLConfig config, EGLContext share, int[] attrib);
    EGLSurface eglCreateWindowSurface(EGLDisplay display, EGLConfig config, Object win, int[] attrib);
    EGLSurface eglCreatePbufferSurface(EGLDisplay display, EGLConfig config, int[] attrib);
    boolean eglDestroyContext(EGLDisplay display, EGLContext context);
    boolean eglDestroySurface(EGLDisplay display, EGLSurface surface);
    boolean eglGetConfigAttrib(EGLDisplay display, EGLConfig config, int attribute, int[] value);
    EGLDisplay eglGetDisplay(Object nativeDisplay);
    int eglGetError();
    boolean eglInitialize(EGLDisplay display, int[] majorMinor);
    boolean eglMakeCurrent(EGLDisplay display, EGLSurface draw, EGLSurface read, EGLContext context);
    boolean eglQuerySurface(EGLDisplay display, EGLSurface surface, int attribute, int[] value);
    String eglQueryString(EGLDisplay display, int name);
    boolean eglSwapBuffers(EGLDisplay display, EGLSurface surface);
    boolean eglTerminate(EGLDisplay display);
    boolean eglWaitGL();
    boolean eglWaitNative(int engine, Object bindTarget);
}
